meta_product_name: "stumbl"
meta_title: "Stumbl - local events for you"
meta_description: "Stumbl - helping you find your next location"
meta_image: "stumbl_wide_3.png" # should exist in `app/assets/images/`
